name: Deploy on Push

on:
  push:
    branches:
      - '**'

jobs:

  deploy-prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Branch info
        run: |
          echo "Branch: main"

      - name: Deploy to prod
        run: |
          echo "Deploying to PROD"

  deploy-dev:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Branch info
        run: |
          echo "Branch: not main"

      - name: Deploy to dev
        run: |
          echo "Deploying to DEV"


