name: Dummy Deploy with Secrets

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Which environment to deploy to"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}

    steps:
      - name: Print environment name
        run: |
          echo "deploy to ${{ github.environment }}"

      - name: Print masked API key
        run: |
          echo "API key is: ${{ secrets.MY_API_KEY }}"

      - name: Print service name
        run: |
          echo "deploying: ${{ vars.SERVICE_NAME }}"

